# Generated by Django 2.0.1 on 2018-01-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCourseDepart',
            fields=[
                ('ccd_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CampusDetail',
            fields=[
                ('campus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=100)),
                ('campus_address', models.CharField(blank=True, max_length=100, null=True)),
                ('campus_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('campus_city', models.CharField(blank=True, max_length=20, null=True)),
                ('campus_country', models.CharField(blank=True, max_length=20, null=True)),
                ('campus_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('campus_logo', models.CharField(max_length=15)),
                ('campus_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterCourse',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDepart',
            fields=[
                ('depart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='campuscoursedepart',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.CampusDetail'),
        ),
        migrations.AddField(
            model_name='campuscoursedepart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.MasterCourse'),
        ),
        migrations.AddField(
            model_name='campuscoursedepart',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.MasterDepart'),
        ),
    ]
