# Generated by Django 2.0.1 on 2018-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusdetail',
            name='campus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
