# Generated by Django 2.0.1 on 2018-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20180123_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusdetail',
            name='campus_logo',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
