# Generated by Django 2.0.1 on 2018-01-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20180123_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDepartment',
            fields=[
                ('depart_id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campuscoursedepart',
            name='ccd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campuscoursedepart',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.MasterDepartment'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mastercourse',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MasterDepart',
        ),
    ]
